"""
xAI Grok 4.5 / 4.6 / Grok Build pricing (docs.x.ai, per 1M tokens).

Public package API — re-exports rates + reconstruction helpers.
Importers should use ``from token_telemetry.pricing import ...``.
"""

from token_telemetry.pricing.rates import (
    CHARS_PER_TOKEN,
    CONTEXT_TIER_THRESHOLD,
    COST_USD_TICKS_PER_USD,
    DEFAULT_MODEL_FAMILY,
    RATES_BY_FAMILY,
    TIER_HIGH,
    TIER_LOW,
    _fit_usd_parts,
    _money_parts,
    _price_cache,
    _price_in,
    _price_out,
    _scale_ints,
    collect_model_hints,
    detect_session_model,
    estimate_cost_usd,
    estimate_from_usage,
    model_family,
    normalize_model_id,
    pick_tier,
    pricing_model_scope,
    pricing_payload,
    rates_for,
    reset_pricing_model,
    resolve_context_for_tier,
    set_pricing_model,
    step_tier_ctx,
    ticks_to_usd,
    usd_to_ticks,
)
from token_telemetry.pricing.reconstruct import reconstruct_model_step_usage

__all__ = [
    "CHARS_PER_TOKEN",
    "CONTEXT_TIER_THRESHOLD",
    "COST_USD_TICKS_PER_USD",
    "DEFAULT_MODEL_FAMILY",
    "RATES_BY_FAMILY",
    "TIER_HIGH",
    "TIER_LOW",
    "_fit_usd_parts",
    "_money_parts",
    "_price_cache",
    "_price_in",
    "_price_out",
    "_scale_ints",
    "collect_model_hints",
    "detect_session_model",
    "estimate_cost_usd",
    "estimate_from_usage",
    "model_family",
    "normalize_model_id",
    "pick_tier",
    "pricing_model_scope",
    "pricing_payload",
    "rates_for",
    "reconstruct_model_step_usage",
    "reset_pricing_model",
    "resolve_context_for_tier",
    "set_pricing_model",
    "step_tier_ctx",
    "ticks_to_usd",
    "usd_to_ticks",
]
